#!/usr/bin/env php
<?php

use Velolia\Console\Console;

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';
$console = new Console($app);
$status = $console->handle($argv);
exit($status);